# 100 NumPy excercises

This is a collection of excercises from the GitHub project [Numpy-100](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb)

1. Import the NumPy package under the name `np`. (★☆☆)

In [1]:
import numpy as np

2. Print the NumPy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.22.4
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

3. Create a null vector of size 10 (★☆☆)

In [3]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array? (★☆☆)

In [4]:
x = np.zeros((10, 10))
print('%d bytes'%(x.size * x.itemsize))

800 bytes


5. How to get the documentation of the NumPy `add` function from the commandline? (★☆☆)

In [5]:
# %run `py -c "import numpy; numpy.info(numpy.add)"`

6. Create a null vector of size 10 but the fifth value which 1 (★☆☆)

In [6]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element become last) (★☆☆)

In [8]:
x = np.arange(20)
x = x[::-1]
x

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find of nonzero elements from [1, 2, 0, 0, 4, 0] (★☆☆)

In [10]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
nz

(array([0, 1, 4], dtype=int64),)

11. Create a 3x3 identity matrix (★☆☆)

In [11]:
x = np.eye(3, 3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
x = np.random.random((3, 3, 3))
x

array([[[0.95687612, 0.43007589, 0.09652087],
        [0.6752862 , 0.60246739, 0.95177293],
        [0.168806  , 0.44045385, 0.40984249]],

       [[0.36078701, 0.20252234, 0.39988161],
        [0.68408167, 0.37184339, 0.32612849],
        [0.47329514, 0.63259069, 0.89308449]],

       [[0.0296851 , 0.79838564, 0.87620724],
        [0.79121608, 0.83086194, 0.13246381],
        [0.87019887, 0.53854825, 0.88657945]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
x = np.random.random((10, 10))
x_min, x_max = x.min(), x.max()
print(x_min, x_max)

0.0002563680897318399 0.9959434802162446


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
x = np.random.random(30)
x.mean()

0.46992342236837203

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

16. How to add a border (filled with 0's) around an exsiting array? (★☆☆)

In [16]:
x = np.ones((5, 5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
x


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
x = np.ones((5, 5))
x[:, [0, -1]] = 0
x[[0, -1], :] = 0
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

17. What is the result of the following expression? (★☆☆)

```py
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagnol (★☆☆)

In [19]:
x = np.diag(1 + np.arange(4), k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

20. Consider a (6, 7, 8) shape array, what is the index (x, y, z) of the 100th element? (★☆☆)

In [21]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

21. Create a checkerboard 8x8 matrix using the `tile` function (★☆☆)

In [22]:
np.tile([[0, 1], [1, 0]], (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
x = np.random.random((5, 5))
x = (x - np.mean(x)) / np.std(x)
x

array([[ 1.30445725,  0.73610925,  1.45914616, -1.45621108,  1.28888341],
       [-0.49301103,  0.18836609,  0.013964  ,  1.45838617,  1.17901517],
       [ 0.0599934 ,  0.0577743 ,  0.67480566, -0.02512584, -0.36587369],
       [-1.58992753, -1.05802305,  0.46211497, -1.45209403, -1.05804325],
       [-0.61449158,  1.41826854,  0.18192537, -0.92762782, -1.44278085]])

23. Create a custom dtype that describe a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype(
    [
        ('r', np.ubyte),
        ('g', np.ubyte),
        ('b', np.ubyte),
        ('a', np.ubyte)
    ]
)
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
np.dot(np.ones((5, 3)), np.ones((3, 2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [26]:
np.ones((5, 3)) @ np.ones((3, 2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

25. Given a 1d array, negate all elements which are between 3 and 8, in place (★☆☆)

In [27]:
x = np.arange(11)
x[(3 < x) & (x < 8)] *= -1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

26. What is the output of the following script? (★☆☆)

```py
    print(sum(range(5),-1))
    from numpy import *
    print(sum(range(5),-1))
```

In [28]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consideer an integer vector Z, which of these expression are legal? (★☆☆)

```py
    Z**Z
    2 << Z >> 2
    Z <- Z
    1j*Z
    Z/1/1
    Z<Z>Z
```

In [29]:
Z = np.arange(10)

# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z (the unlegal expression)

28. What are the resule of the following expression? (★☆☆)

```py
    np.array(0) / np.array(0)
    np.array(0) // np.array(0)
    np.array([np.nan]).astype(int).astype(float)
```

In [30]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


C:\Users\User\AppData\Local\Temp\ipykernel_11000\1729466501.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\User\AppData\Local\Temp\ipykernel_11000\1729466501.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

29. How to round away from zero a float array? (★☆☆)

In [31]:
x = np.random.uniform(-10, 10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([ -3.,  -5.,   2.,  -2., -10.,   9.,   1.,  -4.,   9.,   2.])

30. How to find common values between two arrays? (★☆☆)

In [32]:
x = np.random.randint(0, 10, 10)
y = np.random.randint(0, 10, 10)
np.intersect1d(x, y)

array([0, 2, 4, 8, 9])

31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [33]:
defaults = np.seterr(all='ignore')
x = np.ones(1) / 0

_ = np.seterr(**defaults)

with np.errstate(all='ignore'):
    np.arange(3) / 0

32. Is the following expression True?

```py
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\User\AppData\Local\Temp\ipykernel_11000\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

33. How to get the date of yesterday, today and tomorrow? (★☆☆)

In [35]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(f'Today {today}, yesterday {yesterday}, tomorrow {tomorrow}')

Today 2022-07-02, yesterday 2022-07-01, tomorrow 2022-07-03


34. How to get all the dates corresponding to the month of July 2016? (★☆☆)

In [36]:
x = np.arange('2022-07', '2022-08', dtype='datetime64[D]')
x

array(['2022-07-01', '2022-07-02', '2022-07-03', '2022-07-04',
       '2022-07-05', '2022-07-06', '2022-07-07', '2022-07-08',
       '2022-07-09', '2022-07-10', '2022-07-11', '2022-07-12',
       '2022-07-13', '2022-07-14', '2022-07-15', '2022-07-16',
       '2022-07-17', '2022-07-18', '2022-07-19', '2022-07-20',
       '2022-07-21', '2022-07-22', '2022-07-23', '2022-07-24',
       '2022-07-25', '2022-07-26', '2022-07-27', '2022-07-28',
       '2022-07-29', '2022-07-30', '2022-07-31'], dtype='datetime64[D]')

35. How to compute ((A+B)*(-A/2)) in place (with out copy)? (★★☆)

In [37]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [38]:
x = np.random.uniform(0, 10, 10)

print(x - x%1)
print(x//1)
print(np.floor(x))
print(x.astype(int))
print(np.trunc(x))

[8. 2. 3. 0. 8. 7. 8. 4. 1. 6.]
[8. 2. 3. 0. 8. 7. 8. 4. 1. 6.]
[8. 2. 3. 0. 8. 7. 8. 4. 1. 6.]
[8 2 3 0 8 7 8 4 1 6]
[8. 2. 3. 0. 8. 7. 8. 4. 1. 6.]


37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
x = np.zeros((5, 5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [40]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

38. Consider a generator function that generates 10 integer and use it to build an array (★★☆)

In [41]:
def generator():
    for x in range(10):
        yield x

x = np.fromiter(generator(), dtype=float, count=-1)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [42]:
x = np.linspace(0, 1, 11, endpoint=False)[1:]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

40. Create a random vector of size 10 and sort it (★★☆)

In [43]:
x = np.random.random(10)
x.sort()
x

array([0.11138208, 0.15670819, 0.30540228, 0.47419369, 0.4836225 ,
       0.49597906, 0.58942914, 0.69770665, 0.73665365, 0.93918262])

41. How to sum a small array faster than `np.sum()`? (★★☆)

In [44]:
x = np.arange(10)
np.add.reduce(x)

45

42. Consider two random array A and B, check if they are equal (★★☆)

In [45]:
x = np.random.randint(0, 2, 5)
y = np.random.randint(0, 2, 5)

np.array_equal(x, y)

False

43. Make an array immutable (read-only)? (★★☆)

In [47]:
x = np.zeros(20)
x.flags.writeable = False
try:
    x[0] = 1
except Exception as e:
    print(e)

assignment destination is read-only


44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [48]:
A = np.random.random((10, 5))
X, Y = A[:, 0], A[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.69279308 1.13035939 0.56843811 0.96401826 0.7648231  0.77680309
 0.81505069 0.55273494 1.00302089 0.64928423]
[0.5428198  1.03450424 1.34720594 1.2405619  1.39879529 1.44988538
 1.45069224 0.40001958 0.84498613 0.2160878 ]


45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [49]:
x = np.random.random(10)
x[x.argmax()] = 0
x

array([0.31454447, 0.26652146, 0.02652339, 0.        , 0.39949187,
       0.13951778, 0.01572143, 0.25090338, 0.06635696, 0.17556862])

46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [51]:
Z = np.zeros((5, 5), dtype=[('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(
    np.linspace(0, 1, 5),
    np.linspace(0, 1, 5)
)
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [55]:
x = np.arange(9)
y = x + 0.25
C = 1.0 / np.subtract.outer(x, y)
np.linalg.det(C)

-531433.0472450904

48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [56]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. How to print all the values of an array? (★★☆)

In [60]:
np.set_printoptions(threshold=float('inf'))
x = np.ones((10, 10))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [63]:
x = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(x - v)).argmin()
x[index]

63

51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [64]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\User\AppData\Local\Temp\ipykernel_11000\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [65]:
z = np.random.random((10, 2))
x, y = np.atleast_2d(z[:, 0], z[:, 1])
D = np.sqrt((x - x.T)**2 + (y - y.T)**2)
D

array([[0.        , 0.33325288, 0.62201199, 0.17871349, 0.33561768,
        0.5603865 , 0.48673605, 0.3672857 , 0.15372297, 0.48616638],
       [0.33325288, 0.        , 0.92950945, 0.20694044, 0.56081978,
        0.81149238, 0.62702104, 0.31119459, 0.48631987, 0.39544448],
       [0.62201199, 0.92950945, 0.        , 0.72624433, 0.72734167,
        0.24641933, 0.51749777, 0.77290537, 0.50273998, 0.84184249],
       [0.17871349, 0.20694044, 0.72624433, 0.        , 0.49482662,
        0.60551086, 0.44273545, 0.20798057, 0.32373175, 0.32587805],
       [0.33561768, 0.56081978, 0.72734167, 0.49482662, 0.        ,
        0.77431989, 0.79166766, 0.6979892 , 0.2900447 , 0.81730865],
       [0.5603865 , 0.81149238, 0.24641933, 0.60551086, 0.77431989,
        0.        , 0.28592217, 0.59227642, 0.49563076, 0.63842823],
       [0.48673605, 0.62702104, 0.51749777, 0.44273545, 0.79166766,
        0.28592217, 0.        , 0.34835894, 0.50630691, 0.36550094],
       [0.3672857 , 0.31119459, 0.7729053

In [66]:
import scipy
import scipy.spatial

x = np.random.random((10, 2))
D = scipy.spatial.distance.cdist(x, x)
D

array([[0.        , 0.07840506, 0.29382891, 0.38638953, 0.51731868,
        0.70199929, 0.59827654, 0.78998167, 0.38787614, 0.07560121],
       [0.07840506, 0.        , 0.21589689, 0.31954691, 0.53198413,
        0.74146967, 0.67616561, 0.85298014, 0.45285989, 0.15149193],
       [0.29382891, 0.21589689, 0.        , 0.21627032, 0.6456196 ,
        0.89619853, 0.89202864, 1.04910782, 0.63619977, 0.36728039],
       [0.38638953, 0.31954691, 0.21627032, 0.        , 0.51820816,
        0.79639667, 0.94045743, 1.00825421, 0.77197827, 0.43964799],
       [0.51731868, 0.53198413, 0.6456196 , 0.51820816, 0.        ,
        0.28662562, 0.69331264, 0.56250263, 0.78888078, 0.48732259],
       [0.70199929, 0.74146967, 0.89619853, 0.79639667, 0.28662562,
        0.        , 0.61242253, 0.32566974, 0.85699649, 0.64756868],
       [0.59827654, 0.67616561, 0.89202864, 0.94045743, 0.69331264,
        0.61242253, 0.        , 0.41650463, 0.41865415, 0.5251475 ],
       [0.78998167, 0.85298014, 1.0491078

53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [67]:
x = (np.random.rand(10) * 100).astype(np.float32)
y = x.view(np.int32)
y[:] = x
y

array([88, 18, 96, 78, 98, 29, 63, 64,  0, 72])

54. How to read the following file? (★★☆)

```py
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11.
```

In [70]:
from io import StringIO

s = StringIO(
    '''1, 2, 3, 4, 5
       6,  ,  , 7, 8
        ,  , 9, 10, 11'''
)

x = np.genfromtxt(s, delimiter=',', dtype=np.int32)
x

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [71]:
x = np.arange(10).reshape(5, 2)
print(x)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(3, 0) 6
(3, 1) 7
(4, 0) 8
(4, 1) 9
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(3, 0) 6
(3, 1) 7
(4, 0) 8
(4, 1) 9


56. Generate a generic 2D Gaussian-like array (★★☆)

In [72]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X**2 + Y**2)
sigma, mu = 1.0, 0.0
G = np.exp(-(D - mu)**2 / (2.0 * sigma ** 2))
G

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

57. How to randomly place p elements in a 2D array? (★★☆)

In [73]:
n = 10
p = 3
x = np.zeros((n, n))
np.put(x, np.random.choice(range(n * n), p, replace=False), 1)
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

58. Subtract the mean of each row of a matrix (★★☆)

In [74]:
x = np.random.rand(5, 10)
y = x- x.mean(axis=1, keepdims=True)
y

array([[-0.080961  , -0.45525192,  0.45859179,  0.28729164,  0.32686168,
        -0.35164327,  0.11818799,  0.44407458, -0.3980132 , -0.34913829],
       [ 0.15902884,  0.2393262 , -0.30717149, -0.23369402,  0.04565825,
         0.14259363, -0.24110718, -0.20761731,  0.24619253,  0.15679056],
       [ 0.25129278,  0.15824453, -0.15773466,  0.48747243, -0.14709192,
        -0.21448909,  0.4832261 , -0.2835855 , -0.32204569, -0.25528899],
       [-0.16156054,  0.49281002, -0.42002221, -0.02710961, -0.16023751,
         0.30158636,  0.08279711, -0.27909363,  0.25312101, -0.082291  ],
       [ 0.06862176, -0.42475074,  0.32318853,  0.13632484,  0.3833245 ,
        -0.24880503,  0.05081013, -0.30269915, -0.04043961,  0.05442476]])

59. How to sort an array by the nth column? (★★☆)

In [75]:
x = np.random.randint(0, 10, (3, 3))
print(x)
print(x[x[:, 1].argsort()])

[[0 1 8]
 [7 6 1]
 [6 1 8]]
[[0 1 8]
 [6 1 8]
 [7 6 1]]


60. How to tell if a given 2D array has null columns? (★★☆)

In [76]:
x = np.random.randint(0, 5, (5, 10))
print((~x.any(axis=0)).any())

False


61. Find the nearest value from a given value in an array (★★☆)

In [77]:
x = np.random.uniform(0, 1, 10)
z = 0.5
x.flat[np.abs(x - z).argmin()]

0.4379602033671858

62. Considering two arrays with shape (1, 3) and (3, 1), how to compute their sum using an iterator? (★★☆)

In [79]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
it.operands[2]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

63. Create an array class that has a name attribute (★★☆)

In [80]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name='no name'):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.info = getattr(obj, 'name', 'no name')

x = NamedArray(np.arange(10), 'range_10')
x.name

'range_10'

64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [84]:
x = np.ones(10)
I = np.random.randint(0, len(x), 20)
np.add.at(x, I, 1)
x

array([4., 1., 4., 1., 4., 5., 3., 2., 3., 3.])

65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [85]:
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [86]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
n


64

In [87]:
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64


67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [88]:
x = np.random.randint(0, 10, (3, 4, 4, 3))
sum = np.sum(x, axis=(-2, -1))
sum

array([[37, 60, 44, 48],
       [48, 73, 51, 41],
       [52, 47, 57, 41]])

In [89]:
x.reshape(x.shape[:-2] + (-1, )).sum(axis=-1)

array([[37, 60, 44, 48],
       [48, 73, 51, 41],
       [52, 47, 57, 41]])

68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

In [91]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
D_means

array([0.42469902, 0.57810618, 0.13756408, 0.59095185, 0.30359084,
       0.60373691, 0.37038344, 0.50804338, 0.54384273, 0.61513141])

69. How to get the diagonal of a dot product? (★★★)

In [92]:
x = np.random.uniform(0, 1, (5, 5))
y = np.random.uniform(0, 1, (5, 5))
np.diag(np.dot(x, y))

array([1.13153714, 1.28249714, 2.15246852, 0.58633164, 1.54443302])

In [93]:
np.sum(x * y.T, axis=1)

array([1.13153714, 1.28249714, 2.15246852, 0.58633164, 1.54443302])

In [94]:
np.einsum('ij, ji->i', x, y)

array([1.13153714, 1.28249714, 2.15246852, 0.58633164, 1.54443302])

70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [99]:
x = np.arange(5) + 1
nz = 3
z_0 = np.zeros(len(x) + (len(x) - 1)*(nz))
z_0[::(nz + 1)] = x
z_0

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [100]:
x = np.ones((5, 5, 3))
y = 4 * np.ones((5, 5))
x * y[..., np.newaxis]

array([[[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]]])

72. How to swap two rows of an array? (★★★)

In [103]:
x = np.arange(30).reshape(6, 5)
x[[0, -1]] = x[[-1, 0]]
x

array([[25, 26, 27, 28, 29],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4]])

73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that `np.bincount(A) == C`? (★★★)

In [104]:
C = np.bincount([1, 1, 2, 3, 5, 5, 7])
A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 2, 3, 5, 5, 7])

75. How to compute averages using a sliding window over an array? (★★★)

76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [106]:
x = np.random.randint(0, 5, 100)
np.logical_not(x, out=x)


array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1])

In [107]:
x = np.random.uniform(-1, 1, 100)
np.negative(x, out=x)


array([-0.01554368,  0.65269698,  0.27983389, -0.00853243,  0.88705734,
       -0.90154175,  0.88894866,  0.39282906,  0.7477279 ,  0.86017344,
        0.97771573,  0.9663756 , -0.89609019,  0.51362446,  0.70767521,
       -0.03648142, -0.19632657,  0.2382199 ,  0.77635109,  0.29461813,
       -0.59097945, -0.07364365, -0.43874779,  0.78626334, -0.65760978,
        0.73199579,  0.34346726, -0.59886317, -0.85070036, -0.79474717,
       -0.87972979, -0.29627936,  0.65467677,  0.47279263,  0.71260319,
        0.11163535,  0.89074235, -0.7505812 , -0.98477619, -0.6318157 ,
       -0.60827659, -0.23643225,  0.31969646,  0.1677313 ,  0.86395249,
       -0.83172451, -0.89876853, -0.68640542, -0.49820701, -0.43533142,
        0.72179629,  0.2993713 ,  0.61382485,  0.78155911, -0.2020552 ,
       -0.22010844, -0.62507988,  0.86177305,  0.56531483,  0.55532088,
        0.54134072,  0.38820098, -0.91939984,  0.44874919, -0.08009192,
       -0.14976298,  0.99831945,  0.63497775, -0.67863739, -0.56

78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [108]:
Z = np.arange(1, 15, dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z, (11, 4), (4, 4))
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

82. Compute a matrix rank (★★★)

In [109]:
x = np.random.uniform(0, 1, (10, 10))
rank = np.linalg.matrix_rank(x)
rank

10

83. How to find the most frequent value in an array?

In [111]:
x = np.random.randint(0, 10, 100)
np.bincount(x).argmax()

6

84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

88. How to implement the Game of Life using numpy arrays? (★★★)

89. How to get the n largest values of an array (★★★)

In [112]:
x = np.arange(100000)
np.random.shuffle(x)
n = 10
print(x[np.argsort(x)[-n:]])

[99990 99991 99992 99993 99994 99995 99996 99997 99998 99999]


In [113]:
x[np.argpartition(-x, n)[:n]]

array([99999, 99998, 99995, 99996, 99997, 99994, 99993, 99991, 99992,
       99990])

90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

91. How to create a record array from a regular array? (★★★)

92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [114]:
x = np.random.rand(int(5e7))

%timeit np.power(x, 3)
%timeit x*x*x
%timeit np.einsum('i, i, i -> i', x, x, x)

7.14 s ± 1.19 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
The slowest run took 9.44 times longer than the fastest. This could mean that an intermediate result is being cached.
2.71 s ± 2.67 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
620 ms ± 237 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

95. Convert a vector of ints into a matrix binary representation (★★★)

96. Given a two dimensional array, how to extract unique rows? (★★★)

97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
 